
/* Crear tabla PERSONA */
CREATE TABLE persona
(
   IDPER INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 200 INCREMENT BY 1,
   DNIPER CHAR(8),
   NOMPER VARCHAR2(60),
   APEPER VARCHAR2(80),
   EMAPER VARCHAR2(80),
   CELPER CHAR(9),
   TIPPER CHAR(1),
   ESTPER CHAR(1) DEFAULT 'A',
   FECNACPER DATE,
   CONSTRAINT PER_PK PRIMARY KEY (IDPER)       
);
COMMIT;

/* Ver la estructura de la tabla PERSONA */
SELECT *
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'PERSONA';

/* Listar tablas del schema de base de datos */
select table_name from user_tables;

/* Agregar una columna ESTADO CIVIL en la tabla PERSONA */
ALTER TABLE persona
    ADD ECIV CHAR(1);
COMMIT;

/* Ver estructura de tabla PERSONA con nueva columna */
DESCRIBE persona;



/* Eliminar una columna ESTADO CIVIL en la tabla PERSONA */
ALTER TABLE persona
    DROP COLUMN ECIV;
COMMIT;
/* Ver estructura de tabla PERSONA sin columna ECIV */
DESCRIBE persona;

/* Relacionar tabla VENTA con PERSONA (Cliente) */
ALTER TABLE VENTA 
      ADD CONSTRAINT IDCLI_FK FOREIGN KEY (IDCLI)
      REFERENCES USER_ORACLE.PERSONA (IDPER);
COMMIT;

/* Listar relaciones de la tabla VENTA */
SELECT 
   table_name, 
   constraint_name, 
   constraint_type, 
   r_owner, 
   r_constraint_name 
FROM user_constraints 
WHERE
     TABLE_NAME = 'VENTA' AND CONSTRAINT_TYPE = 'R'; 
     
